---
# tasks file for apache
- name: Install the packages
  yum:
    name: "{{item}}"
    state: present
  loop: "{{package}}"

- name: Enable the service
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  loop: "{{roservice}}"

- name: enable firewall service
  firewalld:
    service: "{{item}}"
    immediate: yes
    permanent: yes
    state: enabled
  loop: "{{fwrules}}"

- name: deploy the template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    setype: httpd_sys_content_t

    