---
- name: Deploy hosts file
  hosts: all
  tasks:
    - name: Deploy the template file for myhosts
      template:
        src: hosts.j2
        dest: /etc/myhosts
      when: "'dev' in group_names"

